### ISSUE TITLE
Consistent website design

### ISSUE THREAD

**Issue by AlexanderKaschta** [PhyPiDAQ/PhyPiDAQ.github.io#1]
Use a static site generator to convert the provided markdown to a consistent looking website. 

Pros:
- Mostly normal Markdown code except lines for metadata, like
```
---
title: "AStA-Serviceangebote"
draft: true
markup: pandoc
weight: 1
---
```
- No more HTML-code or CSS-style in the markdown
- Consistent design over all pages (including responsive design)
- No dependence on external tools to do the conversion and committing those changes

Cons:
- Initial setup is not trivial
- No solution for picture adjustment

Some options:
- GitHub Pages is already supporting jekyll, which would be an option
  - A possible theme around the markdown: https://github.com/pages-themes/cayman
  - Another example using https://academicpages.github.io/

**Comment by GuenterQuast** [comment]
Ich denke, eine index.html erzeugt aus README.md ist einfach, lightweight und auch allgemein ohne zu viel Spezialwissen leicht zu pflegen. Ich möchte das gerne so lassen.Noch ein Punkt: für den Wettbewerb in Prag brauchen wir Inhalte. Formalien können wir dann später klären, falls nötig. Deshalb schreibe ich mit den Werkzeugen, die ich beherrsche und nicht erst lernen muss ...-- Diese Nachricht wurde von meinem Android Mobiltelefon mit 1&1 Mail gesendet.Am 26.02.22, 00:53 schrieb Alexander Kaschta ***@***.***>:

   
  Use a static site generator to convert the provided markdown to a consistent looking website. 
  Pros: 
   
   Mostly normal Markdown code except lines for metadata, like 
   
  ---
title: "AStA-Serviceangebote"
draft: true
markup: pandoc
weight: 1
---
 
   
   No more HTML-code or CSS-style in the markdown 
   Consistent design over all pages (including responsive design) 
   No dependence on external tools to do the conversion and committing those changes 
   
  Cons: 
   
   Initial setup is not trivial 
   No solution for picture adjustment 
   
  Some options: 
   
   GitHub Pages is already supporting jekyll, which would be an option 
     
     A possible theme around the markdown: https://github.com/pages-themes/cayman 
     Another example using https://academicpages.github.io/

**Comment by AlexanderKaschta** [comment]
A working demo can be found [here](https://alexanderkaschta.github.io/PhyPiDAQ.github.io/) or using the direct link: https://alexanderkaschta.github.io/PhyPiDAQ.github.io/

The source code can be found in the fork: https://github.com/AlexanderKaschta/PhyPiDAQ.github.io
(I will use it as a pull-request on a later date, as I couldn't create a branch)

The design isn't final nor all are bugs fixed (no favicon, better logo position, images not centered). Source of the index page is the https://github.com/AlexanderKaschta/PhyPiDAQ.github.io/blob/main/index.md file, which will including all other `*.md` files, be compiled by GitHub to their matching page. As long as there are no changes to the template file required, it is plain markdown with only different links `[Name](./name.html)` instead of `[Name](name.md)`. Except from committing code, there is no need for any user input and no external tools need to be executed by the user to deploy the site. This makes this whole process much easier for people, who only know markdown.
